class ProductGallery {
  static List<String> getImages(String productId, String thumbnail) {
    final Map<String, List<String>> galleries = {
      "b1": [
        "assets/images/bottles/b1/bottle11.png",
        "assets/images/bottles/b1/bottle12.png",
        "assets/images/bottles/b1/bottle13.png",
        "assets/images/bottles/b1/candlee.png",
      ],
      "b2": [
        "assets/images/bottles/b2/bottle2.png",
        "assets/images/bottles/b2/bottle21.png",
        "assets/images/bottles/b2/bottle22.png",
        "assets/images/bottles/b2/bottle23.png",
      ],
      "b3": [
        "assets/images/bottles/b3/bottle3.png",
        "assets/images/bottles/b3/bottle31.png",
        "assets/images/bottles/b3/bottle32.png",
        "assets/images/bottles/b3/bottle33.png",
      ],
      "b4": [
        "assets/images/bottles/b4/bottle4.png",
        "assets/images/bottles/b4/bottle41.png",
        "assets/images/bottles/b4/bottle42.png",
        "assets/images/bottles/b4/bottle43.png",
      ],
      "b5": [
        "assets/images/bottles/b5/bottle5.png",
        "assets/images/bottles/b5/bottle51.png",
        "assets/images/bottles/b5/bottle52.png",
        "assets/images/bottles/b5/bottle53.png",
      ],
      "b6": [
        "assets/images/bottles/b6/bottle6.png",
        "assets/images/bottles/b6/bottle61.png",
        "assets/images/bottles/b6/bottle62.png",
        "assets/images/bottles/b6/bottle63.png",
      ],
      "b7": [
        "assets/images/bottles/b7/bottle7.png",
        "assets/images/bottles/b7/bottle71.png",
        "assets/images/bottles/b7/bottle72.png",
        "assets/images/bottles/b7/bottle73.png",
      ],
      "b8": [
        "assets/images/bottles/b8/bottle8.png",
        "assets/images/bottles/b8/bottle81.png",
        "assets/images/bottles/b8/bottle82.png",
        "assets/images/bottles/b8/bottle83.png",
      ],

      "c1": [
        "assets/images/candle/c1/glass1.png",
        "assets/images/candle/c1/glass11.png",
        "assets/images/candle/c1/glass12.png",
        "assets/images/candle/c1/glass13.png",
      ],
      "c2": [
        "assets/images/candle/c2/glass2.png",
        "assets/images/candle/c2/glass21.png",
        "assets/images/candle/c2/glass22.png",
        "assets/images/candle/c2/glass23.png",
      ],
      "c3": [
        "assets/images/candle/c3/cake1.png",
        "assets/images/candle/c3/cake11.png",
        "assets/images/candle/c3/cake12.png",
        "assets/images/candle/c3/cake13.png",
      ],
      "c4": [
        "assets/images/candle/c4/glass3.png",
        "assets/images/candle/c4/glass31.png",
        "assets/images/candle/c4/glass32.png",
        "assets/images/candle/c4/glass33.png",
      ],
      "c5": [
        "assets/images/candle/c5/macarron.png",
        "assets/images/candle/c5/macarron1.png",
        "assets/images/candle/c5/macarron2.png",
        "assets/images/candle/c5/macarron3.png",
      ],
      "c6": [
        "assets/images/candle/c6/popcorn.png",
        "assets/images/candle/c6/popcorn1.png",
        "assets/images/candle/c6/popcorn2.png",
        "assets/images/candle/c6/popcorn3.png",
      ],
      "c7": [
        "assets/images/candle/c7/crossaint.png",
        "assets/images/candle/c7/crossaint1.png",
        "assets/images/candle/c7/crossaint2.png",
        "assets/images/candle/c7/crossaint3.png",
      ],
      "c8": [
        "assets/images/candle/c8/lemon.png",
        "assets/images/candle/c8/lemon1.png",
        "assets/images/candle/c8/lemon2.png",
        "assets/images/candle/c8/lemon3.png",
      ],
      "c9": [
        "assets/images/candle/c9/glass4.png",
        "assets/images/candle/c9/glass41.png",
        "assets/images/candle/c9/glass42.png",
        "assets/images/candle/c9/glass43.png",
      ],
      "c10": [
        "assets/images/candle/c10/cake2.png",
        "assets/images/candle/c10/cake21.png",
        "assets/images/candle/c10/cake22.png",
        "assets/images/candle/c10/cake23.png",
      ],
      "c11": [
        "assets/images/candle/c11/cake3.png",
        "assets/images/candle/c11/cake31.png",
        "assets/images/candle/c11/cake32.png",
        "assets/images/candle/c11/cake33.png",
      ],
      "c12": [
        "assets/images/candle/c12/glass5.png",
        "assets/images/candle/c12/glass51.png",
        "assets/images/candle/c12/glass52.png",
        "assets/images/candle/c12/glass53.png",
      ],
      "c13": [
        "assets/images/candle/c13/cake4.png",
        "assets/images/candle/c13/cake41.png",
        "assets/images/candle/c13/cake42.png",
        "assets/images/candle/c13/cake43.png",
      ],
      "c14": [
        "assets/images/candle/c14/cake5.png",
        "assets/images/candle/c14/cake51.png",
        "assets/images/candle/c14/cake52.png",
        "assets/images/candle/c14/cake53.png",
      ],
      "c15": [
        "assets/images/candle/c15/glass6.png",
        "assets/images/candle/c15/glass61.png",
        "assets/images/candle/c15/glass62.png",
        "assets/images/candle/c15/glass63.png",
      ],
      "c16": [
        "assets/images/candle/c16/cake6.png",
        "assets/images/candle/c16/cake61.png",
        "assets/images/candle/c16/cake62.png",
        "assets/images/candle/c16/cake63.png",
      ],
      "c17": [
        "assets/images/candle/c17/cake7.png",
        "assets/images/candle/c17/cake71.png",
        "assets/images/candle/c17/cake72.png",
        "assets/images/candle/c17/cake73.png",
      ],
      "c18": [
        "assets/images/candle/c18/cake8.png",
        "assets/images/candle/c18/cake81.png",
        "assets/images/candle/c18/cake82.png",
        "assets/images/candle/c18/cake83.png",
      ],
      "c19": [
        "assets/images/candle/c19/cake9.png",
        "assets/images/candle/c19/cake91.png",
        "assets/images/candle/c19/cake92.png",
        "assets/images/candle/c19/cake93.png",
      ],
      "c20": [
        "assets/images/candle/c20/cake10.png",
        "assets/images/candle/c20/cake101.png",
        "assets/images/candle/c20/cake102.png",
        "assets/images/candle/c20/cake103.png",
      ],
      "c21": [
        "assets/images/candle/c21/cake11.png",
        "assets/images/candle/c21/cake111.png",
        "assets/images/candle/c21/cake112.png",
        "assets/images/candle/c21/cake113.png",
      ],
      "c22": [
        "assets/images/candle/c22/cake12.png",
        "assets/images/candle/c22/cake121.png",
        "assets/images/candle/c22/cake122.png",
        "assets/images/candle/c22/cake123.png",
      ],
      "c23": [
        "assets/images/candle/c23/cake13.png",
        "assets/images/candle/c23/cake131.png",
        "assets/images/candle/c23/cake132.png",
        "assets/images/candle/c23/cake133.png",
      ],

      "ca1": [
        "assets/images/caps/ca1/cap1.png",
        "assets/images/caps/ca1/cap11.png",
        "assets/images/caps/ca1/cap12.png",
        "assets/images/caps/ca1/cap13.png",
      ],
      "ca2": [
        "assets/images/caps/ca2/cap2.png",
        "assets/images/caps/ca2/cap21.png",
        "assets/images/caps/ca2/cap22.png",
        "assets/images/caps/ca2/cap23.png",
      ],
      "ca3": [
        "assets/images/caps/ca3/cap3.png",
        "assets/images/caps/ca3/cap31.png",
        "assets/images/caps/ca3/cap32.png",
        "assets/images/caps/ca3/cap33.png",
      ],
      "ca4": [
        "assets/images/caps/ca4/cap4.png",
        "assets/images/caps/ca4/cap41.png",
        "assets/images/caps/ca4/cap42.png",
        "assets/images/caps/ca4/cap43.png",
      ],
      "ca5": [
        "assets/images/caps/ca5/cap5.png",
        "assets/images/caps/ca5/cap51.png",
        "assets/images/caps/ca5/cap52.png",
        "assets/images/caps/ca5/cap53.png",
      ],
      "ca6": [
        "assets/images/caps/ca6/cap6.png",
        "assets/images/caps/ca6/cap61.png",
        "assets/images/caps/ca6/cap62.png",
        "assets/images/caps/ca6/cap63.png",
      ],
      "ca7": [
        "assets/images/caps/ca7/cap7.png",
        "assets/images/caps/ca7/cap71.png",
        "assets/images/caps/ca7/cap72.png",
        "assets/images/caps/ca7/cap73.png",
      ],
      "ca8": [
        "assets/images/caps/ca8/cap8.png",
        "assets/images/caps/ca8/cap81.png",
        "assets/images/caps/ca8/cap82.png",
        "assets/images/caps/ca8/cap83.png",
      ],

      "ce1": [
        "assets/images/ceramic/ce1/cup1.png",
        "assets/images/ceramic/ce1/cup11.png",
        "assets/images/ceramic/ce1/cup12.png",
        "assets/images/ceramic/ce1/cup13.png",
      ],
      "ce2": [
        "assets/images/ceramic/ce2/cup2.png",
        "assets/images/ceramic/ce2/cup21.png",
        "assets/images/ceramic/ce2/cup22.png",
        "assets/images/ceramic/ce2/cup23.png",
      ],
      "ce3": [
        "assets/images/ceramic/ce3/cup3.png",
        "assets/images/ceramic/ce3/cup31.png",
        "assets/images/ceramic/ce3/cup32.png",
        "assets/images/ceramic/ce3/cup33.png",
      ],
      "ce4": [
        "assets/images/ceramic/ce4/cup4.png",
        "assets/images/ceramic/ce4/cup41.png",
        "assets/images/ceramic/ce4/cup42.png",
        "assets/images/ceramic/ce4/cup43.png",
      ],
      "ce5": [
        "assets/images/ceramic/ce5/cup5.png",
        "assets/images/ceramic/ce5/cup51.png",
        "assets/images/ceramic/ce5/cup52.png",
        "assets/images/ceramic/ce5/cup53.png",
      ],
      "ce6": [
        "assets/images/ceramic/ce6/cup6.png",
        "assets/images/ceramic/ce6/cup61.png",
        "assets/images/ceramic/ce6/cup62.png",
        "assets/images/ceramic/ce6/cup63.png",
      ],
      "ce7": [
        "assets/images/ceramic/ce7/cup7.png",
        "assets/images/ceramic/ce7/cup71.png",
        "assets/images/ceramic/ce7/cup72.png",
        "assets/images/ceramic/ce7/cup73.png",
      ],
      "ce8": [
        "assets/images/ceramic/ce8/cup8.png",
        "assets/images/ceramic/ce8/cup81.png",
        "assets/images/ceramic/ce8/cup82.png",
        "assets/images/ceramic/ce8/cup83.png",
      ],

      "h1": [
        "assets/images/hair_accessories/h1/bearband.png",
        "assets/images/hair_accessories/h1/bearband1.png",
        "assets/images/hair_accessories/h1/bearband2.png",
        "assets/images/hair_accessories/h1/bearband3.png",
      ],
      "h2": [
        "assets/images/hair_accessories/h2/band1.png",
        "assets/images/hair_accessories/h2/band11.png",
        "assets/images/hair_accessories/h2/band12.png",
        "assets/images/hair_accessories/h2/band13.png",
      ],
      "h3": [
        "assets/images/hair_accessories/h3/clip.png",
        "assets/images/hair_accessories/h3/clip1.png",
        "assets/images/hair_accessories/h3/clip2.png",
        "assets/images/hair_accessories/h3/clip3.png",
      ],
      "h4": [
        "assets/images/hair_accessories/h4/crown.png",
        "assets/images/hair_accessories/h4/crown1.png",
        "assets/images/hair_accessories/h4/crown2.png",
        "assets/images/hair_accessories/h4/crown3.png",
      ],
      "h5": [
        "assets/images/hair_accessories/h5/band2.png",
        "assets/images/hair_accessories/h5/band21.png",
        "assets/images/hair_accessories/h5/band22.png",
        "assets/images/hair_accessories/h5/band23.png",
      ],
      "h6": [
        "assets/images/hair_accessories/h6/clutch.png",
        "assets/images/hair_accessories/h6/clutch1.png",
        "assets/images/hair_accessories/h6/clutch2.png",
        "assets/images/hair_accessories/h6/clutch3.png",
      ],
      "h7": [
        "assets/images/hair_accessories/h7/band3.png",
        "assets/images/hair_accessories/h7/band31.png",
        "assets/images/hair_accessories/h7/band32.png",
        "assets/images/hair_accessories/h7/band33.png",
      ],
      "h8": [
        "assets/images/hair_accessories/h8/clutch2.png",
        "assets/images/hair_accessories/h8/clutch21.png",
        "assets/images/hair_accessories/h8/clutch22.png",
        "assets/images/hair_accessories/h8/clutch23.png",
      ],

      "k1": [
        "assets/images/key_chain/k1/star.png",
        "assets/images/key_chain/k1/star1.png",
        "assets/images/key_chain/k1/star2.png",
        "assets/images/key_chain/k1/star3.png",
      ],
      "k2": [
        "assets/images/key_chain/k2/idbag.png",
        "assets/images/key_chain/k2/idbag1.png",
        "assets/images/key_chain/k2/idbag2.png",
        "assets/images/key_chain/k2/idbag3.png",
      ],
      "k3": [
        "assets/images/key_chain/k3/catkey.png",
        "assets/images/key_chain/k3/catkey1.png",
        "assets/images/key_chain/k3/catkey2.png",
        "assets/images/key_chain/k3/catkey3.png",
      ],
      "k4": [
        "assets/images/key_chain/k4/dogkey.png",
        "assets/images/key_chain/k4/dogkey1.png",
        "assets/images/key_chain/k4/dogkey2.png",
        "assets/images/key_chain/k4/dogkey3.png",
      ],
      "k5": [
        "assets/images/key_chain/k5/teddykey.png",
        "assets/images/key_chain/k5/teddykey1.png",
        "assets/images/key_chain/k5/teddykey2.png",
        "assets/images/key_chain/k5/teddykey3.png",
      ],
      "k6": [
        "assets/images/key_chain/k6/teddyman.png",
        "assets/images/key_chain/k6/teddyman1.png",
        "assets/images/key_chain/k6/teddyman2.png",
        "assets/images/key_chain/k6/teddyman3.png",
      ],
      "k7": [
        "assets/images/key_chain/k7/cattykey.png",
        "assets/images/key_chain/k7/cattykey1.png",
        "assets/images/key_chain/k7/cattykey2.png",
        "assets/images/key_chain/k7/cattykey3.png",
      ],
      "k8": [
        "assets/images/key_chain/k8/alpa.png",
        "assets/images/key_chain/k8/alpa1.png",
        "assets/images/key_chain/k8/alpa2.png",
        "assets/images/key_chain/k8/alpa3.png",
      ],

      "n1": [
        "assets/images/nails/n1/nail1.png",
        "assets/images/nails/n1/nail11.png",
        "assets/images/nails/n1/nail12.png",
        "assets/images/nails/n1/nail13.png",
      ],
      "n2": [
        "assets/images/nails/n2/nail2.png",
        "assets/images/nails/n2/nail21.png",
        "assets/images/nails/n2/nail22.png",
        "assets/images/nails/n2/nail23.png",
      ],
      "n3": [
        "assets/images/nails/n3/nail3.png",
        "assets/images/nails/n3/nail31.png",
        "assets/images/nails/n3/nail32.png",
        "assets/images/nails/n3/nail33.png",
      ],
      "n4": [
        "assets/images/nails/n4/nail4.png",
        "assets/images/nails/n4/nail41.png",
        "assets/images/nails/n4/nail42.png",
        "assets/images/nails/n4/nail43.png",
      ],
      "n5": [
        "assets/images/nails/n5/nail5.png",
        "assets/images/nails/n5/nail51.png",
        "assets/images/nails/n5/nail52.png",
        "assets/images/nails/n5/nail53.png",
      ],
      "n6": [
        "assets/images/nails/n6/nail6.png",
        "assets/images/nails/n6/nail61.png",
        "assets/images/nails/n6/nail62.png",
        "assets/images/nails/n6/nail63.png",
      ],
      "n7": [
        "assets/images/nails/n7/nail7.png",
        "assets/images/nails/n7/nail71.png",
        "assets/images/nails/n7/nail72.png",
        "assets/images/nails/n7/nail73.png",
      ],
      "n8": [
        "assets/images/nails/n8/nail8.png",
        "assets/images/nails/n8/nail81.png",
        "assets/images/nails/n8/nail82.png",
        "assets/images/nails/n8/nail83.png",
      ],

      "p1": [
        "assets/images/plusie/p1/cat.png",
        "assets/images/plusie/p1/cat1.png",
        "assets/images/plusie/p1/cat2.png",
        "assets/images/plusie/p1/cat3.png",
      ],
      "p2": [
        "assets/images/plusie/p2/dino.png",
        "assets/images/plusie/p2/dino1.png",
        "assets/images/plusie/p2/dino2.png",
        "assets/images/plusie/p2/dino3.png",
      ],
      "p3": [
        "assets/images/plusie/p3/deer.png",
        "assets/images/plusie/p3/deer1.png",
        "assets/images/plusie/p3/deer2.png",
        "assets/images/plusie/p3/deer3.png",
      ],
      "p4": [
        "assets/images/plusie/p4/horn.png",
        "assets/images/plusie/p4/horn1.png",
        "assets/images/plusie/p4/horn2.png",
        "assets/images/plusie/p4/horn3.png",
      ],
      "p5": [
        "assets/images/plusie/p5/rabbit.png",
        "assets/images/plusie/p5/rabbit1.png",
        "assets/images/plusie/p5/rabbit2.png",
        "assets/images/plusie/p5/rabbit3.png",
      ],
      "p6": [
        "assets/images/plusie/p6/racoon.png",
        "assets/images/plusie/p6/racoon1.png",
        "assets/images/plusie/p6/racoon2.png",
        "assets/images/plusie/p6/racooon3.png",
      ],
      "p7": [
        "assets/images/plusie/p7/doggy.png",
        "assets/images/plusie/p7/doggy1.png",
        "assets/images/plusie/p7/doggy2.png",
        "assets/images/plusie/p7/doggy3.png",
      ],
      "p8": [
        "assets/images/plusie/p8/rabbitfruit.png",
        "assets/images/plusie/p8/rabbitfruit1.png",
        "assets/images/plusie/p8/rabbitfruit2.png",
        "assets/images/plusie/p8/rabbitfruit3.png",
      ],

      "boy_friend_1": ["assets/images/boy_friend/bf1.JPG"],
      "boy_friend_2": ["assets/images/boy_friend/bf10.JPG"],
      "boy_friend_3": ["assets/images/boy_friend/bf11.JPG"],
      "boy_friend_4": ["assets/images/boy_friend/bf12.JPG"],
      "boy_friend_5": ["assets/images/boy_friend/bf2.JPG"],
      "boy_friend_6": ["assets/images/boy_friend/bf3.JPG"],
      "boy_friend_7": ["assets/images/boy_friend/bf4.JPG"],
      "boy_friend_8": ["assets/images/boy_friend/bf5.JPG"],
      "boy_friend_9": ["assets/images/boy_friend/bf6.JPG"],
      "boy_friend_10": ["assets/images/boy_friend/bf7.JPG"],
      "boy_friend_11": ["assets/images/boy_friend/bf8.JPG"],
      "boy_friend_12": ["assets/images/boy_friend/bf9.JPG"],

      "girl_friend_1": ["assets/images/girl_friend/gf1.JPG"],
      "girl_friend_2": ["assets/images/girl_friend/gf10.JPG"],
      "girl_friend_3": ["assets/images/girl_friend/gf11.JPG"],
      "girl_friend_4": ["assets/images/girl_friend/gf12.JPG"],
      "girl_friend_5": ["assets/images/girl_friend/gf13.JPG"],
      "girl_friend_6": ["assets/images/girl_friend/gf14.JPG"],
      "girl_friend_7": ["assets/images/girl_friend/gf15.JPG"],
      "girl_friend_8": ["assets/images/girl_friend/gf2.JPG"],
      "girl_friend_9": ["assets/images/girl_friend/gf3.JPG"],
      "girl_friend_10": ["assets/images/girl_friend/gf4.JPG"],
      "girl_friend_11": ["assets/images/girl_friend/gf5.JPG"],
      "girl_friend_12": ["assets/images/girl_friend/gf6.JPG"],
      "girl_friend_13": ["assets/images/girl_friend/gf7.JPG"],
      "girl_friend_14": ["assets/images/girl_friend/gf8.JPG"],
      "girl_friend_15": ["assets/images/girl_friend/gf9.JPG"],
    };

    return galleries[productId] ?? [thumbnail];
  }
}